// Generated by gencpp from file robotis/counterRequest.msg
// DO NOT EDIT!


#ifndef ROBOTIS_MESSAGE_COUNTERREQUEST_H
#define ROBOTIS_MESSAGE_COUNTERREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace robotis
{
template <class ContainerAllocator>
struct counterRequest_
{
  typedef counterRequest_<ContainerAllocator> Type;

  counterRequest_()
    : mystring()  {
    }
  counterRequest_(const ContainerAllocator& _alloc)
    : mystring(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _mystring_type;
  _mystring_type mystring;





  typedef boost::shared_ptr< ::robotis::counterRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robotis::counterRequest_<ContainerAllocator> const> ConstPtr;

}; // struct counterRequest_

typedef ::robotis::counterRequest_<std::allocator<void> > counterRequest;

typedef boost::shared_ptr< ::robotis::counterRequest > counterRequestPtr;
typedef boost::shared_ptr< ::robotis::counterRequest const> counterRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robotis::counterRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robotis::counterRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::robotis::counterRequest_<ContainerAllocator1> & lhs, const ::robotis::counterRequest_<ContainerAllocator2> & rhs)
{
  return lhs.mystring == rhs.mystring;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::robotis::counterRequest_<ContainerAllocator1> & lhs, const ::robotis::counterRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace robotis

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::robotis::counterRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robotis::counterRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robotis::counterRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robotis::counterRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robotis::counterRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robotis::counterRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robotis::counterRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e8054fff057e825e73968032a7c26bc8";
  }

  static const char* value(const ::robotis::counterRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe8054fff057e825eULL;
  static const uint64_t static_value2 = 0x73968032a7c26bc8ULL;
};

template<class ContainerAllocator>
struct DataType< ::robotis::counterRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robotis/counterRequest";
  }

  static const char* value(const ::robotis::counterRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robotis::counterRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string mystring\n"
"\n"
;
  }

  static const char* value(const ::robotis::counterRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robotis::counterRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.mystring);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct counterRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robotis::counterRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robotis::counterRequest_<ContainerAllocator>& v)
  {
    s << indent << "mystring: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.mystring);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOTIS_MESSAGE_COUNTERREQUEST_H
