// Generated by gencpp from file robotis/mahmoud.msg
// DO NOT EDIT!


#ifndef ROBOTIS_MESSAGE_MAHMOUD_H
#define ROBOTIS_MESSAGE_MAHMOUD_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace robotis
{
template <class ContainerAllocator>
struct mahmoud_
{
  typedef mahmoud_<ContainerAllocator> Type;

  mahmoud_()
    : x(0)
    , y(0)  {
    }
  mahmoud_(const ContainerAllocator& _alloc)
    : x(0)
    , y(0)  {
  (void)_alloc;
    }



   typedef int32_t _x_type;
  _x_type x;

   typedef int32_t _y_type;
  _y_type y;





  typedef boost::shared_ptr< ::robotis::mahmoud_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robotis::mahmoud_<ContainerAllocator> const> ConstPtr;

}; // struct mahmoud_

typedef ::robotis::mahmoud_<std::allocator<void> > mahmoud;

typedef boost::shared_ptr< ::robotis::mahmoud > mahmoudPtr;
typedef boost::shared_ptr< ::robotis::mahmoud const> mahmoudConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robotis::mahmoud_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robotis::mahmoud_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::robotis::mahmoud_<ContainerAllocator1> & lhs, const ::robotis::mahmoud_<ContainerAllocator2> & rhs)
{
  return lhs.x == rhs.x &&
    lhs.y == rhs.y;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::robotis::mahmoud_<ContainerAllocator1> & lhs, const ::robotis::mahmoud_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace robotis

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::robotis::mahmoud_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robotis::mahmoud_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robotis::mahmoud_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robotis::mahmoud_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robotis::mahmoud_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robotis::mahmoud_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robotis::mahmoud_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bd7b43fd41d4c47bf5c703cc7d016709";
  }

  static const char* value(const ::robotis::mahmoud_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xbd7b43fd41d4c47bULL;
  static const uint64_t static_value2 = 0xf5c703cc7d016709ULL;
};

template<class ContainerAllocator>
struct DataType< ::robotis::mahmoud_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robotis/mahmoud";
  }

  static const char* value(const ::robotis::mahmoud_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robotis::mahmoud_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 x\n"
"int32 y\n"
;
  }

  static const char* value(const ::robotis::mahmoud_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robotis::mahmoud_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct mahmoud_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robotis::mahmoud_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robotis::mahmoud_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<int32_t>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<int32_t>::stream(s, indent + "  ", v.y);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOTIS_MESSAGE_MAHMOUD_H
